POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer ...

{
  "title": "yesdh",
  "author": "foooorrr",
  "url": "https://yahoo.it",
  "likes": 2
}


###

POST http://localhost:3003/api/blogs/653e9ef7e4cdf343d43d1a21/comments
Content-Type: application/json
Authorization: Bearer ...

{
  "comment": "first comment"
}

###

POST http://localhost:3003/api/users/
Content-Type: application/json

{
  "name": "Clemens",
  "username": "root",
  "password": "password"
}


###

POST http://localhost:3001/api/login/
Content-Type: application/json

{
  "username": "master3",
  "password": "password"
}

###

POST http://localhost:3003/api/testing/reset
